# Copyright (C) 2026 Eugenia Cames. Personal/portfolio project. All rights reserved.

#Metadata
spring.application.name=reading-tracker

#DB connection
spring.datasource.url=jdbc:postgresql://dummy-example
spring.datasource.username=example-username
spring.datasource.password=example-password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
